### ISSUE TITLE
It slows down ioBroker

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.coronavirus-statistics#10]
First: This is a very useful program and I would like to thank the programmer.

But:
I use a Raspberry 4, actually fast enough.
However, I have a rather slow internet connection.
It is around 9.7 Mbit / s.

If the instance is installed, the connection to the script page is interrupted every 15 minutes. So whenever the app updates.
In addition, ioBroker then does not respond to my voice instructions.

It would be great if the data that was needed were adjustable.
I personally only need "global", "Germany" and "Norway".

**Comment by Apollon77** [comment]
For the country selection an other issue already exists or?! Then this is duplicate. 

For your performance issue: the adapter creates and updates roughly 1000
States ... maybe lower the frequency of execution?

**Comment by Michaelnorge** [comment]
My entry is to be seen as a supplement to entry #7 !! 
As a result, my entry is not a double one. As an addition, I announced a low bandwidth as a problem.
A lower frequency makes no sense, since the problem is less frequent but still occurs.

**Comment by DutchmanNL** [comment]
I agree its not double but in line with feature request of https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/7

Low bandwidth is absolutely not the issue trust me, the whole object array is just an JSON object retrieved with a single API. call so even a bandwith of 0.5 mb is strong enough to get the data within a second.

But exposing the. 1000+ objects can be an issue on low performance systems and by that slowing down your device.

I will keep the issue open until the filter is implemented to verify with you if that solves your specific issue ok ?  :)

**Comment by Michaelnorge** [comment]
Ja dat is goed, bedankt @DutchmanNL en veel gezondheit gewenst !

**Comment by DutchmanNL** [comment]
> Ja dat is goed, bedankt @DutchmanNL en veel gezondheit gewenst !

interessant, google translate gebruikt of werkelijke iemand de Nederlandse taal machtig ? :)

For everyone : Country selection implemented in version 0.3.0 states for not selected countries will be automatically removed with this version !

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/2f6b0d782f4339a1539c4090535d8b73d9a829db

thank you @GermanBluefox
