### ISSUE TITLE
Add 7 day incidence for all countries

### ISSUE THREAD

**Issue by ratte-rizzo** [iobroker-community-adapters/ioBroker.coronavirus-statistics#116]
Hi

Thanks for this really great adapter! One nice to have enhancement is the 7 day incidence for all countries. This would ease the post processing a lot.

Thanks for listening
Daniel

**Comment by ppb1308** [comment]
Hello,
i like to ask, if you can add for widget the possibility to choice not only country data but also values from extended properties tab like: 
- Bundesländer
- Landkreise
- Städte
Thanks,
regards,
Peter

**Comment by DutchmanNL** [comment]
> Hi
> 
> Thanks for this really great adapter! One nice to have enhancement is the 7 day incidence for all countries. 

sorry but that data is not present in API : https://corona.lmao.ninja/docs/#/COVID-19%3A%20Worldometers/get_v3_covid_19_countries

**Comment by ratte-rizzo** [comment]
> > Hi
> > Thanks for this really great adapter! One nice to have enhancement is the 7 day incidence for all countries.
> 
> sorry but that data is not present in API : https://corona.lmao.ninja/docs/#/COVID-19%3A%20Worldometers/get_v3_covid_19_countries

I expected this already, so it would have been nice to compute it internally in the adapter instead of in an own script. 

Anyway, thanks for checking. 
Daniel
