### ISSUE TITLE
Add timestamp of last successful data refresh for cities or counties

### ISSUE THREAD

**Issue by mesche** [iobroker-community-adapters/ioBroker.coronavirus-statistics#119]
The timestamp of last successful data refresh is only available for federal states but not for cities or counties.

In my opinion it would make sense to extend this for all types, because the data can be updated independently.

Thank you

**Comment by DutchmanNL** [comment]
implemented in 0.6.4

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/15118c7e8ec396dc72c6326c189181b631525ea6
