### ISSUE TITLE
The countries cannot be selected.

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.coronavirus-statistics#12]
Germany is switched on by default, but it´s not possible to select other countries.

_(Ik ben Nederlands maar geboren in Duitsland.
Ik kan Nederlands verstaan, maar ik kan het niet schrijven.
Ik heb tante Google nodig om te helpen :-) )_

**Comment by DutchmanNL** [comment]
update of yesterday did break the select function, working on it

**Comment by DutchmanNL** [comment]
fixed 0.3.3

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/9d02f78d0f0a38ca56bdd79f686aaacdc773e0d6
