### ISSUE TITLE
Top 5 countries

### ISSUE THREAD

**Issue by lapidu** [iobroker-community-adapters/ioBroker.coronavirus-statistics#13]
Can you add a category Top 10 countries of cases and death?

**Comment by DutchmanNL** [comment]
sure will do, nice one

**Comment by DutchmanNL** [comment]
💃 

version 0.3.5 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/8d165d38a1ad65b70b884dd48a9e678ac7f190bd

<img width="411" alt="Schermafbeelding 2020-03-23 om 22 23 11" src="https://user-images.githubusercontent.com/7318445/77364759-36f69980-6d55-11ea-8f50-e382b97bedbd.png">
