### ISSUE TITLE
Add Covid Vaccination Coverage from RKI 

### ISSUE THREAD

**Issue by ninja-warrior** [iobroker-community-adapters/ioBroker.coronavirus-statistics#141]
Good evening guys,

first of all: Thanks a lot for that great adapter! I use the adapter a lot in different scenarios.

I just figured out that RKI also provides Covid Vaccination Coverage for all german federal states:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html

As far as I understand, RKI always provides "data from yesterday" (absolut and delta). Would be great to include that information as new datapoints to country and federl states of germany. 

Best regards,
David

**Comment by DutchmanNL** [comment]
hi, thanks :)

as far as I can see this data ist not available by API ?

**Comment by DutchmanNL** [comment]
<img width="845" alt="Schermafbeelding 2020-12-28 om 21 55 57" src="https://user-images.githubusercontent.com/7318445/103242734-a68a5c80-4957-11eb-938f-8345e286df47.png">
<img width="873" alt="Schermafbeelding 2020-12-28 om 21 56 21" src="https://user-images.githubusercontent.com/7318445/103242738-a8542000-4957-11eb-9cfc-4dfc69f779ce.png">
<img width="916" alt="Schermafbeelding 2020-12-28 om 21 56 45" src="https://user-images.githubusercontent.com/7318445/103242739-a9854d00-4957-11eb-9a92-c4dd79211eb6.png">

**Comment by ninja-warrior** [comment]
Can you extract the data using an appropriate RegEX-Pattern?

Or otherwise, maybe I can find another website providing the information with matching api.

**Comment by winnyschuster** [comment]
> Can you extract the data using an appropriate RegEX-Pattern?
> Or otherwise, maybe I can find another website providing the information with matching api.

right now, this data is only available as an Excel, so no possibility of using RegEx. As an interim, i'll provide this data with a script but first need to see how that Excel will look like next days. Have a look at [the forum](https://forum.iobroker.net/category/93/javascript), i'll announce it there. first draft looks good already

**Comment by DutchmanNL** [comment]
@winnyschuster 

the easiest  why i guess would be this parser  Module to read and parse the xls just as json and have It handled as current json objects in the adapter.

https://www.npmjs.com/package/xls-parser

**Comment by DutchmanNL** [comment]
Hmm I found one for all countries and will implement it soon! 
but no separation for DE sorry just country level

**Comment by ninja-warrior** [comment]
Thanks a lot for your effort. Looking forward to test the new feature soon.

**Comment by DutchmanNL** [comment]
i checked the API data, not relevant info found except the medicine data.
Adding the xls part just for Germany is not really adding value, as soon a country wide API is available we can look at it
