### ISSUE TITLE
 [germanyFederalStates] error: Cannot read property '2' of null, stack: TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by chrkraus** [iobroker-community-adapters/ioBroker.coronavirus-statistics#148]
Hello, 

I will get after the newest update following error message in the log.

Can you have a look on it?

coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:615:5)
-- | -- | -- | --
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:312:37)
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at Covid19.getGermanyVaccinationData (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:796:27)
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at runMicrotasks (<anonymous>)
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | at getInfos (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:780:80)
coronavirus-statistics.0 | 2021-01-04 14:36:18.333 | error | (2268) [germanyFederalStates] error: Cannot read property '2' of null, stack: TypeError: Cannot read property '2' of null

Thanks
Christian

**Comment by xdaamg** [comment]
Nach einem Downgrade auf 0.6.5 tritt der Fehler bei mir auch auf. Die Liste der Bundesländer ist leer, es werden keine Objekte hierfür erzeugt. Die Impfzahlen werden nicht aktualisiert.
Und was mir noch auffällt ist, dass die Exceldatei "Impfungen" auf der RKI-Seite einige Nullwerte in Datenfeldern aufweist ("Veränderung seit gestern"), falls das auch ein Problem sein könnte.

**Comment by chrkraus** [comment]
Bei mir tritt der Fehler nach einem Upgrade von 0.6.4 auf 0.6.6 auf. Die "Impfungen" bekomme ich gar nicht angezeigt.

**Comment by DutchmanNL** [comment]
ah great I missed an error handling in the Germany vaccination data.....
thanks guys will check

**Comment by DutchmanNL** [comment]
solved 0.6.7
https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/releases/tag/v0.6.7
