### ISSUE TITLE
Some strange logs...

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.coronavirus-statistics#15]
That´s in my log by starting the adapter:

coronavirus-statistics.0 | 2020-03-23 16:43:00.881 | info | (31228) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
coronavirus-statistics.0 | 2020-03-23 16:43:00.407 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:59.980 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:59.729 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:59.433 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:59.095 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:58.792 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:58.557 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:58.451 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:58.450 | warn | (31228) Turks_and_Caicos not found in lib! Must be added to the country name translator.
coronavirus-statistics.0 | 2020-03-23 16:42:58.250 | warn | (31228) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-23 16:42:58.000 | warn | (31228) State attribute definition missing for + countryInfo

**Comment by DutchmanNL** [comment]
fixed 0.3.4 :)

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/2c7df7bb970cfae93dc61ef838b23eaa8258a50c
