### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Dragon0501** [iobroker-community-adapters/ioBroker.coronavirus-statistics#151]
Changelog says added the Impfungen pro 1000. There is no Datapoint containing the information.

**Comment by DutchmanNL** [comment]
> Changelog says added the Impfungen pro 1000. There is no Datapoint containing the information.

which version do you have installed ? Did you activate "bundeslaender" ?

**Comment by Dragon0501** [comment]
Problem solved! Bundesländer wasn't activated

**Comment by DutchmanNL** [comment]
> Problem solved! Bundesländer wasn't activated

thanks I will add that to the readme, reason is that I only have the data for Germany based o Bundeslaender so I only want to get it if activated to not stress the api unneeded for all countries. Still no vac data in api of all countries

**Comment by EagleeyeKai** [comment]
Are the vaccination data points „only“ available on bundesländer level? The data points on federal level are not updated sind january 16th.
