### ISSUE TITLE
die Berechnung der Faelle pro Million bei den Kontinenten scheint falsch zu sein.

### ISSUE THREAD

**Issue by PapaH1** [iobroker-community-adapters/ioBroker.coronavirus-statistics#16]
In der Berechnung der Cases per Million scheint ein Fehler zu sein.
Beispiel Amerika:
![Amerika](https://user-images.githubusercontent.com/62184881/77351612-4d452b00-6d3e-11ea-8745-d9a65e702849.png)

Active: 48380
casesPerOneMillion 2198
48380 Cases/2198 casesPerOne Million = 22,01 Mio (Einwohner)
Dies würde bedeuten, dass Amerika ca 22 Mio Einwohner hätte.
Laut Wikipedia hat Amerika jedoch 911 Mio Einwohner.

Die Berechnung der casesPerOneMillion muss also lauten: 
48380 Cases/911 Mio = 53,1 casesPerOne Million

Das gleiche gilt für die anderen Kontinente.

**Comment by Scrounger** [comment]
Wie kommst du zu der Erkenntnis das die Berechnung falsch ist?

![grafik](https://user-images.githubusercontent.com/6370451/77344369-5a105180-6d33-11ea-9af8-4c5662a61e3b.png)
![grafik](https://user-images.githubusercontent.com/6370451/77344419-6b595e00-6d33-11ea-8f24-43a042be504a.png)

Also wenn ich die Zahlen addiere komme ich auf 28.747 -> passt also die Berechnung für .World_Sum.

**Comment by PapaH1** [comment]
Sorry für die verspätete Erklärung (siehe oben). 
Ich bin körperbehindert und brauchte Assistenz zur detailierten Beschreibung. Danke für deine Mühe!

**Comment by DutchmanNL** [comment]
> Sorry für die verspätete Erklärung (siehe oben).
> Ich bin körperbehindert und brauchte Assistenz zur detailierten Beschreibung. Danke für deine Mühe!

Danke für die mühe !

**Comment by Scrounger** [comment]
> 
> 
> Sorry für die verspätete Erklärung (siehe oben).
> Ich bin körperbehindert und brauchte Assistenz zur detailierten Beschreibung. Danke für deine Mühe!

@PapaH1 
vielen Dank für die ausführliche Erläuterung. 
Du hast vollkommen recht, die Berechnung stimmt hier nicht, weil ich einfach nur die Werte `casesPerOneMillion` der einzelnen Länder zusammen addiert habe.
Werd ich versuchen zu korrigieren.

Vielen Dank fürs Mitdenken :-)

**Comment by DutchmanNL** [comment]
Danke euch beide ! 

Da sieht man mal wieder wie wichtig es ist Fehler gut zu umschreiben, und das ohne Einsatz anderer (was ihn diesem Fall sigaretten schwierig war) man nicht immer alles sieht ☺️

**Comment by Scrounger** [comment]
Korrekte Berechnung in #32 enthalten

**Comment by DutchmanNL** [comment]
danke @Scrounger commit merged
