### ISSUE TITLE
Vaccination KPIs have not been updated since 16.01.2021 

### ISSUE THREAD

**Issue by ninja-warrior** [iobroker-community-adapters/ioBroker.coronavirus-statistics#160]
Hey guys,

the vaccinaction KPIs for federal states and Germany have not been updated since 16.01.2021 anymore. It looks like [RKI-Impfquotenmonitoring](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) has changed the file format again. Maybe, this is the reason for that behaviour.

Would be nice if you can adapt the parser script to new file format.

Thanks a lot in advance!

Best regards,
David

**Comment by DutchmanNL** [comment]
yes have seen it in the error report will check today thank you !

**Comment by xdaamg** [comment]
RKI verlinkt auf die Seite https://impfdashboard.de/
Die statistischen Daten sind über die Seite dort verteilt (Anzahl Impfungen, Zweitimpfungen, Impfungen Vortag, Indikation). Ob das besser zu parsen ist?

**Comment by jhg28** [comment]
Any news here?

**Comment by Elvissimo** [comment]
just also was wondering about „no progress in vaccinations“ - maybe this project could help?
https://github.com/ard-data/2020-rki-impf-archive

**Comment by xdaamg** [comment]
Eine Datenquelle wäre ja schon da. Das ist die TSV-Datei, die auf der RKI-Seite verlinkt ist (siehe oben). Das ist eine einfache, strukturierte Textdatei und wäre relativ einfach zu verarbeiten. Die Verarbeitung der Exceldatei wäre für die Impfdaten dann nicht mehr erforderlich.

**Comment by DutchmanNL** [comment]
working on it

**Comment by DutchmanNL** [comment]
[Fixed release v0.6.8](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/c00c0f39ef480e5d9ca754b3bcea713fc5eb0368)
