### ISSUE TITLE
Länder in der VIS werden nicht mehr Angezeigt.

### ISSUE THREAD

**Issue by detafun** [iobroker-community-adapters/ioBroker.coronavirus-statistics#165]
Weltweit wird noch Angezeigt.
  
![grafik](https://user-images.githubusercontent.com/44980055/105573234-4de28f80-5d5c-11eb-9b6b-2bb4f15a88a7.png)

Sobald ich das umstelle auf Deutschland oder Italien egal was, ist nur alles leer.

**Comment by xdaamg** [comment]
Nach einem Neustart des Adapters war das Problem verschwunden und trat nicht mehr auf seitdem.

**Comment by DutchmanNL** [comment]
[Fixed release v0.6.8](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/c00c0f39ef480e5d9ca754b3bcea713fc5eb0368)

ab und zu wurden die werte nicht richtig geudated
