### ISSUE TITLE
Datenpunkt "countryInfo" zeigt keinen richtigen Wert

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.coronavirus-statistics#18]
In den Datenpunkten "countryInfo" wird [object Object] ausgegeben.

**Comment by DutchmanNL** [comment]
> In den Datenpunkten "countryInfo" wird [object Object] ausgegeben.

die datenpunkie wurden fehlerhaft erstellt.
am best Adapter mal neu installieren https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/772e292d5abebd56a0ed2a8cec2a8596579bbcff

**Comment by Seqway** [comment]
Trotz Neustart des Adapters sowie kompletter Neustart Iobroker ist country Info noch immer drin.

Ausserdem habe ich neuersdings einen Datenpunkt flag ?

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/40624961/77387448-bef89580-6d8d-11ea-91ae-610b0a3fdfb2.png">
