### ISSUE TITLE
Thousands-Sign for Numbers

### ISSUE THREAD

**Issue by jack-blackson** [iobroker-community-adapters/ioBroker.coronavirus-statistics#2]
First of all, thanks for the adapter!

I have just one idea for improvement. Even though it is quite sad, but the numbers are raising in most countries, and already reached thousands. To read it better, would it be possible to add a thousands sign (e.g. 1.200) to the widget? Or is this something which should be done via css?

Kind regards,
Jack

**Comment by DutchmanNL** [comment]
@GermanBluefox suggestions ?

**Comment by Scrounger** [comment]
#3 enthalten

**Comment by DutchmanNL** [comment]
danke @Scrounger !
