### ISSUE TITLE
Löschen alter States aus Vorversionen

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.coronavirus-statistics#21]
Möglichkeit einbauen, die alten verweisten states zu entfernen, die aus früherer Version übrig geblieben sind. Siehe https://forum.iobroker.net/post/399321

**Comment by DutchmanNL** [comment]
hmm, ehrlich ich glaube es geht nur um einen state momentan der da nicht sein soll oder ?

**Comment by crunchip77** [comment]
Ja, richtig, oder wenn man wie ich voreilig installiert, und alles angelegt hat

**Comment by DutchmanNL** [comment]
> Ja, richtig, oder wenn man wie ich voreilig installiert, und alles angelegt hat

hmm ... ja also Fehler der API usw im code abfangen halte ich fuer richtig,  diese Sachen schwieriger :)

Was durch die api gekommen ist (dieser infoCountry) kan ich hardcoded rausschmeißen.
Die anderen (beispiel laender gestern) nicht ohne. da ne komplett neue routine fuer zu bauen 

Ich sage dan mal so

Fehler im alpha (von git installiert) = selber lösen
Fehler entstanden in Beta oder Prod im code fixen (also wen aus admin per NPM installiert als package

**Comment by crunchip77** [comment]
Geht ja um  countryinfo, haben ja noch mehrere die erstinstallation, also auch die states noch drinstehen. Wegen alpha version hattest du ja gestern schon geschrieben, manuell selber löschen.

**Comment by DutchmanNL** [comment]
sollte sich mit 0.4.6 erledigt haben 💃 

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/5961f3cfc367fa2f6193828c5f5422621af7e2a2#diff-7a9076d6d94e62c13d641aa71f19ae8eR98
