### ISSUE TITLE
Issue with Federal states of Germany

### ISSUE THREAD

**Issue by KLVN** [iobroker-community-adapters/ioBroker.coronavirus-statistics#22]
**Describe the bug**  
If Federal states are enabled, the log will be spammed with
```
coronavirus-statistics.0 | 2020-03-24 19:09:57.649 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
coronavirus-statistics.0 | 2020-03-24 19:09:57.503 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
coronavirus-statistics.0 | 2020-03-24 19:09:57.314 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
coronavirus-statistics.0 | 2020-03-24 19:09:57.125 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
coronavirus-statistics.0 | 2020-03-24 19:09:56.997 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
coronavirus-statistics.0 | 2020-03-24 19:09:56.895 | warn | (2047) State attribute definition missing for + deathsPerOneMillion
```

**To Reproduce**  
1. Enable "Federal states" (and "Get every federal state", not sure if this is the English translation, I use ioBroker in German language)
2. Stop, Start, Reload Corona-Adapter
3. Open log

**Expected behavior**  
No warnings in the log file :D

**Screenshots & Logfiles**  
see above.

**Versions:**  
 - Adapter version: 0.4.0
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: Raspbian Buster

**Additional context**  
Looks like this line is involved: https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/blob/147324ecba3f7ac85b34ec84c5f9872afc56dc12/main.js#L258

**Comment by DutchmanNL** [comment]
Solved => 0.4.2
