### ISSUE TITLE
München is shown twice in the options (and LK München missing?)

### ISSUE THREAD

**Issue by mswiege** [iobroker-community-adapters/ioBroker.coronavirus-statistics#25]
In version 0.4.5 in the advanced settings, the county "München" is shown twice (and selecting one will save both but in the objects, there is obviously just one "München"). 
Since I couldn't find the county "Landkreis München" I assume that simply one of these two "Münchens" is supposed to be the LK but since they are called the same it is not possible to select it (or the city is not selectable and only the LK is, who knows).

**Comment by DutchmanNL** [comment]
Danke,

Habe den Fehler gefunden, ich verwende das attribute GEN was einen allgemein Namen hat, es gibt ein attribute county das hat aber nen Vorsatz und sieht damit scheisse aus :/

Das auch dof aus, if wuerde sagen gruppieren auf Landkreis und "Kreisfreie Stadt" oder ?
<img width="1266" alt="Schermafbeelding 2020-03-25 om 23 48 32" src="https://user-images.githubusercontent.com/7318445/77592749-254af880-6ef3-11ea-970c-a30e7c9c0cf1.png">

```
  {
    "LK Altenburger Land": {
      "GEN": "Altenburger Land",
      "county": "LK Altenburger Land",
      "BEZ": "Landkreis"
    }
  },
  {
    "SK Berlin Reinickendorf": {
      "GEN": "Berlin Reinickendorf",
      "county": "SK Berlin Reinickendorf",
      "BEZ": "Kreisfreie Stadt"
    }
```

**Comment by DutchmanNL** [comment]
solved, wir unterschieden jetzt Städte und kreise 

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/ed77b1fb5d84d70ff5242fc6e6d3d9eae56280ed#diff-7a9076d6d94e62c13d641aa71f19ae8eR385-R400
