### ISSUE TITLE
Hallo,

### ISSUE THREAD

**Issue by smaragdschlange** [iobroker-community-adapters/ioBroker.coronavirus-statistics#26]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by DutchmanNL** [comment]
I think here is missing something?
