### ISSUE TITLE
Für einige Länder fehlt "cases per million", bzw. es wird "1" angezeigt

### ISSUE THREAD

**Issue by gidhap** [iobroker-community-adapters/ioBroker.coronavirus-statistics#28]
Zuerst einmal DANKE und Respekt für die tolle Arbeit, auch wenn das Thema Corona selbst weniger angenehm ist.

Ich weiss nicht ob das Problem mit den gelieferten Werten oder der App selbst zusammenhängt.
Bei mir fehlen bei einigen Ländern seit zwei Tagen die "cases per million", d.h. es steht dort nur die Ziffer 1. Z.B. Italien und Spanien.
![grafik](https://user-images.githubusercontent.com/28500973/77753590-1a46b400-702a-11ea-9449-00793176adc2.png)
Habe auch schon eine neue Instanz angelegt, dabei ändert sich nichts.

**Comment by gidhap** [comment]
Hat sich erledigt, gerade kamen die Daten rein. Lag wohl an der Bereitstellung

**Comment by DutchmanNL** [comment]
Danke für die Rückmeldung 

Sollte das wieder passieren mal schauen ob die Daten dan in der api fehlen und ne Alternative besser ist aber allgemein ist die api schon ok

**Comment by gidhap** [comment]
@DutchmanNL Hallo, seit gestern 13:00 fehlen wieder einige Werte, z.B. USA. Kann ich hier irgendwo versuchen den Fehler einzukreisen ?

**Comment by DutchmanNL** [comment]
> @DutchmanNL Hallo, seit gestern 13:00 fehlen wieder einige Werte, z.B. USA. Kann ich hier irgendwo versuchen den Fehler einzukreisen ?

Mit der Umstellung auf ISO standarte wurde USA in United States geändert.

![Schermafbeelding 2020-04-06 om 11 50 57](https://user-images.githubusercontent.com/7318445/78545969-f5f29080-77fc-11ea-9c65-36a6777ba83b.png)

**Comment by gidhap** [comment]
OK, danke. damit beginnt dann die Historie für USA (jetzt United States) neu !?

**Comment by gidhap** [comment]
DANKE !
