### ISSUE TITLE
Top 5 Abfrage

### ISSUE THREAD

**Issue by Kampfratte** [iobroker-community-adapters/ioBroker.coronavirus-statistics#29]
Bei der Top5 wird nicht nach Cases sortiert. Dazu müsste im Moment USA vor China sein und nicht anders herum.

Du frägst nur per API https://corona.lmao.ninja/all ab. Da bleibt China an erster stelle. Für die Top5 müsstest du aber https://corona.lmao.ninja/countries?sort=cases abrufen, damit die Top5 dann auch in der richtigen Reihenfolge geschrieben werden.

**Comment by Kampfratte** [comment]
Habe dir einen Pull Request mit der geänderten Zeile geschickt. Die Daten der Abfrage sind die selben, nur die Sortierreihenfolge ist anders so dass dies nun für die Top 5 passt.

**Comment by DutchmanNL** [comment]
ich danke dir ! pull merged https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/d2cca49262d4420cdd9c63b0ae7da62de45e924e
