### ISSUE TITLE
New Cases

### ISSUE THREAD

**Issue by lapidu** [iobroker-community-adapters/ioBroker.coronavirus-statistics#30]
Wäre es möglich **yesterdayCases** und **yesterdayDeaths** zu implementieren?

**Comment by Kampfratte** [comment]
Die API gibt diese Zahlen leider nicht her.

**Comment by DutchmanNL** [comment]
koennte man als Berechnung einbauen ... hmm wen richtig bedarf kann man drüber nachdenken ich habe jetzt erstmal die Städte und kreise richtig eingebunden

**Comment by Kampfratte** [comment]
Ich habe mir ein kleines Java-Script gebaut, welches ich per Chronjob einmal pro Tag ausführen lasse. Mit diesem Cronjob werden kurz vor 0 Uhr nachts (ab ca. 22 Uhr kommen eh keine neuen Zahlen mehr rein) dann die todaycases nach neuinfizierte geschrieben. Diese loggt dann bei Änderung automatisch in die SQL-Datenbank, so dass ich dann eine Liste von täglich infizierten habe, die ich über Flot im Balkendiagramm ausgeben kann.

**Comment by lapidu** [comment]
@Kampfratte würdest du dieses Script zur Verfügung stellen? Danke!

**Comment by Kampfratte** [comment]
createState('javascript.0.Corvid-19.Neuinfizierte', 0, {unit: "", name: "neu Infizierte D", type: "number", role: "value"});
  
schedule('58 23 * * *', function (Corvid) {

    var neue1 = getState('coronavirus-statistics.0.Germany.todayCases').val;
    setState('javascript.0.Corvid-19.Neuinfizierte', (neue1), true);

});

Das ist alles.

**Comment by lapidu** [comment]
@ Danke

**Comment by Scrounger** [comment]
@Kampfratte 

Das wird so aber nur bedingt funktionieren, da auch Werte nach 0h noch rein kommen. Liegt an der Zeitzonen der jeweiligen Länder.

Z.b. gestern kam die letzte Aktualisierung erst um 01.49h:
![grafik](https://user-images.githubusercontent.com/6370451/77991771-000c1f00-7325-11ea-9fd4-9bf4d6d6b8b2.png)

**Comment by Kampfratte** [comment]
@Scrounger mir ging es dabei nur um die Zahlen in Deutschland. Nicht weltweit.

**Comment by DutchmanNL** [comment]
da ich die Daten nicht consequent zu zeit x als vorigen tage bestempeln kan werde ich es auch nicht im adapter integrieren (währe schein Funktionalität)

Man kann sich mit script oder Daten logging behelfen wo gewuenst.
