### ISSUE TITLE
state update

### ISSUE THREAD

**Issue by intruder7777** [iobroker-community-adapters/ioBroker.coronavirus-statistics#33]
Please only update states if a change has also been made.

**Comment by DutchmanNL** [comment]
will do in 0.5.0

**Comment by DutchmanNL** [comment]
probier mal bitte von git ob es mit der letzten aenderung behoben ist.

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/98df2957bf5f4d8354e22d5046858133de605b10

**Comment by intruder7777** [comment]
installiert.... ich beobachte

**Comment by intruder7777** [comment]
sieht gut aus !! Top!

**Comment by DutchmanNL** [comment]
Danke, wieder was gelernt über State creation 😒

**Comment by DutchmanNL** [comment]
released https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/145f27bd3bdeafb32085a16149f1955ff0e54378

**Comment by intruder7777** [comment]
ich muss den issue wieder hochholen, da selbiges Problem jetzt wieder vorhanden ist

**Comment by DutchmanNL** [comment]
dublicate,  lass es uns. bei einem issue halten :)
https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/39

komische ist das es funktioniert hat.
