### ISSUE TITLE
World_Sum und global_totals

### ISSUE THREAD

**Issue by Kampfratte** [iobroker-community-adapters/ioBroker.coronavirus-statistics#34]
Hallo

ich hätte da mal eine Frage. Der Zweig World_Sum und global_total zeigt doch die Zahlen Weltweit ein. Müssten dann die Zahlen der einzelnen nicht identisch sein? Das sind sie bei mir nämlich nicht, wie man dem angehängten Screen entnehmen kann.
<img width="1183" alt="Bildschirmfoto 2020-03-29 um 13 00 48" src="https://user-images.githubusercontent.com/37498878/77847490-a3dabb00-71bd-11ea-89a2-3e8059f3058c.png">

**Comment by DutchmanNL** [comment]
@Scrounger world Sum wird anders berechnet oder aus deiner function ?
global totals kommt 1:1 aus der API

**Comment by Kampfratte** [comment]
Guten morgen. Habe gerade mal ein bisschen mit dem Taschenrechner gespielt. Dabei fiel mir auf, dass die Zahlen des World_Sum die Summe der Kontinente ist. Somit scheint es passiert zu sein, dass beim einen oder anderen Kontinent ein Land fehlt. Habe aber noch nicht gefunden, wo die Kontinente definiert werden um alles weiter zu checken.

**Comment by DutchmanNL** [comment]
die kommen aus einer library : https://www.npmjs.com/package/country-list-js

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/blob/master/main.js#L82-L183

**Comment by Kampfratte** [comment]
Ok, ich habe es herausgefunden. Nach vielem Probieren. Es liegt an der Berechnung der Kontinente. Alle Länder haben Kontinente, ist klar. Diese werden auch zusammen gezählt für die World_Sum. Nur ein Datensatz fehlt und dieses hat keinen Kontinent. Es ist der Datensatz "Diamond_Princess". Wenn mich nicht alles täuscht, war das doch ein Schiff auf hoher See. Und das sind diese 712 Cases, die fehlen. Damit fehlen dann nur noch 2 Cases. Wo die fehlen, konnte ich bisher aber noch nicht heraus bekommen.

**Comment by DutchmanNL** [comment]
> Es ist der Datensatz "Diamond_Princess".

Oh lol wieder dieses schiff, danke fuer die Analyse @Kampfratte !

Ehm ... @Scrounger .... nog Ideen dachte das wahre mit der neuen lib richtig :P ?

**Comment by Scrounger** [comment]
Es gibt sogar zwei schiffe ;-)

**Comment by Kampfratte** [comment]
Oha, sogar 2? Mir war nur eins bekannt. Und daran erinnerte ich mich erst wieder, als ich die Liste sah. Dann kann ich mir auch denken, wie die anderen 2 fehlenden Cases geblieben sind. Denn das zweite Schiff ist nicht in der Liste mit drin.

Aber da gebe ich dir recht. Ich denke auch, dass die bereits in den Statistiken ihrer Länder mit drin sind und dadurch doppelt gelistet werden. So weit habe ich garnicht gedacht. Dann würde ich sagen, würde es ja passen.

hängt dann nur noch von @DutchmanNL ab.

**Comment by DutchmanNL** [comment]
released 0.5.4
