### ISSUE TITLE
ioBroker Version auf 0.4.0

### ISSUE THREAD

**Issue by nightout80** [iobroker-community-adapters/ioBroker.coronavirus-statistics#35]
Hi,

vielen Dank für den den Adapter.

In meiner ioBroker Instanz wird der Adapter nicht aktualisiert und steht auf Version 0.4.0. Des Weitern werden die Zahlen außer für Deutschland nicht mehr aktualisiert. Handelt es sich hierbei um ein lokales Problem?

Viele Grüße,
Bastian

**Comment by Kampfratte** [comment]
Instanz mal neu gestartet oder auch den ganzen iobroker mal neu gestartet?

**Comment by DutchmanNL** [comment]
Sieht schwer nach einem lokalen Problem aus

Lösche mal den Adapter komplett (nicht nur die Instanz) und installiere neu

**Comment by nightout80** [comment]
Moin Leute, 

auch meine Vermutung, habe mir die neue Version direkt via GitHub installiert. Bei Deinstallieren hatte ich die "Angst" meine InfluxDB Anbindung  zu verlieren.

**Comment by DutchmanNL** [comment]
Und klappt es damit ?

**Comment by nightout80** [comment]
konnte die Version 0.5.0 direkt darüberinstallieren und hat wunderbar funktioniert

**Comment by DutchmanNL** [comment]
super danke, dan mach ich hier mal zu :)
