### ISSUE TITLE
[v0.5.1] Instance crash loop

### ISSUE THREAD

**Issue by volkerverkamp** [iobroker-community-adapters/ioBroker.coronavirus-statistics#37]
**Describe the bug**  
Crash loop of adapter instance. Instance is constantly restarting ( Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason).

**To Reproduce**  
1. Start instance

**Expected behavior**  
Instance not crashing.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/51383556/78427714-5b674580-7674-11ea-8c49-5936beb3d41b.png)

**Versions:**  
 - Adapter version: 0.5.1
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: Raspbian Buster

Additional info:
Already tried the following to solve the problem:
- delete full objecte tree and restart adapter
- update latest version vom Github

Adapter configuration:

[system.adapter.coronavirus-statistics.0.json.txt](https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/files/4431211/system.adapter.coronavirus-statistics.0.json.txt)

**Comment by DutchmanNL** [comment]
> Crash loop of adapter instance. Instance is constantly restarting ( Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason).

this is not a bug but works as designed, scheduled adapters terminate after execution and start again at scheduled cron.
