### ISSUE TITLE
History Fortschreibung auch bei gleichen Werten

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.coronavirus-statistics#39]
Gefühlt seit dem letzten Update werden History-Werte in sql.0 auch geschrieben, wenn diese nicht geändert wurden. Bei anderen Adaptern habe ich das Problem nicht.

Einstellung History:

![image](https://user-images.githubusercontent.com/39200469/78458571-aa33d000-76b2-11ea-8da4-9c077e922af1.png)

Geschriebene Werte (ich habe den Aufruf auf 3 Stunden runter gesetzt:

![image](https://user-images.githubusercontent.com/39200469/78458588-ce8fac80-76b2-11ea-982a-3e4ef6519756.png)

Verhalten tritt erst nach letztem Update auf:

![image](https://user-images.githubusercontent.com/39200469/78458609-0565c280-76b3-11ea-9421-c0e95db47e9e.png)

Danke für den Adapter!

Gruß, Ralf

**Comment by DutchmanNL** [comment]
Hmm 🤔 seltsam an dem Teil des Codes nix geändert 

Von welche auf welche Version Hast de geüpdatet?

**Comment by RK62** [comment]
Also jetzt bin ich auf der V0.5.1 Was ich vorher hatte weiss ich nicht mehr.
Sonst lösche ich die States mal alle und lasse die neu anlegen und aktiviere die History neu.

**Comment by RK62** [comment]
States heue morgen alle gelöscht, neu angelegt und History sql.0 neu aktiviert. 
Bleibt so: Gleiche Werte werden fortgeschrieben.
Ist aber nicht so schlimm, bei 4 Abfragen am Tag kommt da nicht so viel zusammen.

**Comment by Apollon77** [comment]
Wenn ist das ein sql/History Thema. Bitte mal History/sql neu starten.  Wenn es dann immer noch so ist bitte debug log bei sql/History einschalten und dann log ansehen. Da steht an sich ganz genau warum er was tut

**Comment by intruder7777** [comment]
bei mir das selbe.... siehe anderes Issue

**Comment by DutchmanNL** [comment]
@Apollon77 

kan es sein das dieser extend object das verursacht ?
(bei states. mach ich sowas nicht, wen ja ist das ein problem des Datenlogger Adapters 

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/blob/master/main.js#L515-L520

setstate wird normal ausgeführt.

**Comment by Apollon77** [comment]
Ja das kann sein. Wenn ein Objekt geändert ist dann schreibt history/sql ggf den initalwert. Das wäre blöd wenn das Objejt eigentlich nciht geändert ist. ALso ja das kann sein und ist dann aber wie gesagt sql/history topic :-) Bitte dort issue anlegen

**Comment by intruder7777** [comment]
@DutchmanNL magst du dann bitte das Issue dort anlegen? :-) ich denke dir fällt es einfacher die fachlichen Hintergründe zu beschreiben ;-)

**Comment by DutchmanNL** [comment]
relation https://github.com/ioBroker/ioBroker.js-controller/issues/762

**Comment by DutchmanNL** [comment]
> @DutchmanNL magst du dann bitte das Issue dort anlegen? :-) ich denke dir fällt es einfacher die fachlichen Hintergründe zu beschreiben ;-)

damit warten wir noch aber ich bin mit Ingo in Gespräch wie wir das fixen werden in LongTherm

**Comment by DutchmanNL** [comment]
ok fix sollte an 2 Seiten stattfinden : 

1 - Adapter sollte nicht unnötig states Extender, das ist aber schwierig bei nem sheduled adapter
2 - Die datenlogger sollten ihren custom Teil prüfen und nur bei aenderungen agieren

Zu 1 hab ich momentan keine Lösung, 2 setze ich mich mal ran bei den 3 (history/influx/SQL)

**Comment by DutchmanNL** [comment]
issue created for related adapters, must be solved there time to close here :)
