### ISSUE TITLE
Zahlen werden nicht mehr aktualisiert

### ISSUE THREAD

**Issue by futurelook** [iobroker-community-adapters/ioBroker.coronavirus-statistics#40]
Seit dem letzten Update werden bei mir die Daten nicht mehr aktualisiert. Das letzte Update ist laut Anzeige vom Samstag 04.04.2020. 

Neustart des Adapters hat keine Verbesserung gebracht.

**Comment by DutchmanNL** [comment]
mach mal bitte screenshot vom Datenpunkt wen du mit der maus drauf zeigst, ich glaube der wert last update aus der API stimmt nicht bei mir kommt alles rein.

Sollte auch hier kein update zu sehen sein bitte mehr details um welche werte es geht.

![Schermafbeelding 2020-04-06 om 12 02 42](https://user-images.githubusercontent.com/7318445/78546943-8da4ae80-77fe-11ea-867d-50e686d550dd.png)

**Comment by futurelook** [comment]
Hallo, 

hab gerade geschaut, bei den Ländern (hier: Deutschland) werden keine
Werte aktualisiert (siehe germany.jpg) nur bei global_totals kommen
"frische" Daten rein (siehe global_totals.jpg)

---
Mit freundlichen Grüßen 

Marc André Freiheit 

Am 06-04-2020 12:03, schrieb Dutchman:

> mach mal bitte screenshot vom Datenpunkt wen du mit der maus drauf zeigst, ich glaube der wert last update aus der API stimmt nicht bei mir kommt alles rein. 
> 
> Sollte auch hier kein update zu sehen sein bitte mehr details um welche werte es geht. 
> 
> [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/7318445/78546943-8da4ae80-77fe-11ea-867d-50e686d550dd.png
[2]
https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/40#issuecomment-609699321
[3]

**Comment by futurelook** [comment]
Warum auch immer, jetzt kommen die Daten wieder rein

**Comment by DutchmanNL** [comment]
> Warum auch immer, jetzt kommen die Daten wieder rein

eventuell hatte die API nen hickup, moeglich :)
