### ISSUE TITLE
Testing Update to js-controller 3

### ISSUE THREAD

**Issue by eric2905** [iobroker-community-adapters/ioBroker.coronavirus-statistics#41]
Updated the js-controller to v3.

Log entry

coronavirus-statistics.0	2020-04-08 20:15:23.110	warn	(8779) This object will not be created in future versions. Please report this to the developer.
coronavirus-statistics.0	2020-04-08 20:15:23.109	warn	(8779) Object countryTranslator is invalid: obj.type has to exist

**Comment by Apollon77** [comment]
Please check again with js-controller 3.0.4! Should be fixed

**Comment by eric2905** [comment]
No more log entries.
Fixed

**Comment by DutchmanNL** [comment]
> No more log entries.
> Fixed

Thank you
