### ISSUE TITLE
This endpoint has been deprecated...Values missing

### ISSUE THREAD

**Issue by gidhap** [iobroker-community-adapters/ioBroker.coronavirus-statistics#43]
Hi,
today I discovered I am missing values, restart did not hep. So I checked the Log
`

coronavirus-statistics.0 | 2020-04-17 11:45:24.021 | info | (13670) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
coronavirus-statistics.0 | 2020-04-17 11:45:24.020 | error | (13670) [loadCountries]  error: 410 - "{\"message\":\"This endpoint has been deprecated. Use  /v2/countries instead.\",\"docs\":\"http://corona.lmao.ninja/docs\"}",  stack: StatusCodeError: 410 - "{\"mes
coronavirus-statistics.0 | 2020-04-17 11:45:23.859 | error | (13670) [loadAll] error:  410 - "{\"message\":\"This endpoint has been deprecated. Use /v2/all  instead.\",\"docs\":\"http://corona.lmao.ninja/docs\"}", stack:  StatusCodeError: 410 - "{\"message\":\"Thi
coronavirus-statistics.0 | 2020-04-17 11:45:14.521 | info | (13670) starting. Version 0.5.5 in /opt/iobroker/node_modules/iobroker.coronavirus-statistics, node: v10.19.0
coronavirus-statistics.0 | 2020-04-17 11:39:06.652 | info | (13547) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
coronavirus-statistics.0 | 2020-04-17 11:39:06.651 | error | (13547) [loadCountries]  error: 410 - "{\"message\":\"This endpoint has been deprecated. Use  /v2/countries instead.\",\"docs\":\"http://corona.lmao.ninja/docs\"}",  stack: StatusCodeError: 410 - "{\"mes
coronavirus-statistics.0 | 2020-04-17 11:39:06.513 | error | (13547) [loadAll] error:  410 - "{\"message\":\"This endpoint has been deprecated. Use /v2/all  instead.\",\"docs\":\"http://corona.lmao.ninja/docs\"}", stack:  StatusCodeError: 410 - "{\"message\":\"Thi
coronavirus-statistics.0 | 2020-04-17 11:39:03.619 | info | (13547) starting. Version 0.5.5 in /opt/iobroker/node_modules/iobroker.coronavirus-statistics, node: v10.19.0

`

**Comment by DutchmanNL** [comment]
thank you, beta testing finished, 0.5.6 will be available after 2 PM

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/c6fc1b3967a682af043382401dfdc7a15377e1a9

**Comment by DutchmanNL** [comment]
pending : https://github.com/ioBroker/ioBroker.repositories/pull/713
