### ISSUE TITLE
The County UK does not dispaly in the coronavirus-statistics widget

### ISSUE THREAD

**Issue by seelmkrl** [iobroker-community-adapters/ioBroker.coronavirus-statistics#44]
The County UK does not display in the coronavirus-statistics widget,
For all other countries does it works fine, but not for county UK.

The data for the UK are available in the Iobroker

**Comment by DutchmanNL** [comment]
@GermanBluefox can you please assist I don't get the widget part :)

**Comment by GermanBluefox** [comment]
:(

**Comment by DutchmanNL** [comment]
is this still the case ?
