### ISSUE TITLE
Adapter wird nicht beendet

### ISSUE THREAD

**Issue by Kampfratte** [iobroker-community-adapters/ioBroker.coronavirus-statistics#45]
Guten morgen zusammen

ich habe des öfteren das Problem, dass der Adapter nach der API-Abfrage sich nicht beendet und ich dann nur folgende Fehlermeldung bekomme. Wenn ich dann pkill io.corona im Shell eingebe, läuft der Adapter wieder ne Zeit lang wie gewohnt.

<img width="881" alt="Bildschirmfoto 2020-04-24 um 07 48 42" src="https://user-images.githubusercontent.com/37498878/80179239-63296280-8600-11ea-8289-69b1b924481c.png">

**Comment by DutchmanNL** [comment]
Hi @Kampfratte, danke nice catch !
Es kann tatsächlich passieren das er in nen try catch laeuft ohne termination ist in 0.5.9 behoben bitte testen

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/9d2128cf010256d2cea469ef60c0c75046d2e7b2#diff-7a9076d6d94e62c13d641aa71f19ae8eR515-R520

**Comment by Kampfratte** [comment]
@DutchmanNL ist installiert. Kann aber ein paar Tage dauern, da dieses Phänomen nicht jeden Tag auftritt.

**Comment by Kampfratte** [comment]
@DutchmanNL update auf 0.5.9 hat nichts gebracht. Seit heute nachmittag um 14:15 Uhr wieder das selbe Problem, bzw. selben Logeinträge.

**Comment by DutchmanNL** [comment]
Hmm kan es definitief nicht reproduzieren gibt es irgendwelche andere log Einträge ?

**Comment by Kampfratte** [comment]
Leider nein. Sonst hätte ich selbst schon nachgeschaut.

**Comment by Kampfratte** [comment]
<img width="1230" alt="Bildschirmfoto 2020-04-27 um 20 17 09" src="https://user-images.githubusercontent.com/37498878/80406285-1bd2f880-88c4-11ea-902c-637fa0b48c6f.png">
das ist der komplette Log. Das rote ist das beenden des Adapters mit pkill io.corona, welches ich nun per java alle 15 min ausführen lasse, falls er sich mal wieder nicht alleine beenden lässt.

**Comment by Kampfratte** [comment]
Hab gerade noch mal rein geschaut. der pkill is heute wieder sehr oft, also beendet sich das Widget öfters nicht von alleine. Muss allerdings dazu sagen, dass heute auchn Update des js-controllers kam, welches ich machte.
