### ISSUE TITLE
Upgrade from 0.57 to 0.59 fails

### ISSUE THREAD

**Issue by epcos71** [iobroker-community-adapters/ioBroker.coronavirus-statistics#46]
Hello,

I try to update the adapter from version 0.57 to 0.59 but it fails. Log details here:

*2020-04-26 14:09:21.883  - [32minfo[39m: host.server iobroker upgrade coronavirus-statistics
2020-04-26 14:09:23.001  - [32minfo[39m: host.server iobroker Update coronavirus-statistics from @0.5.7 to @0.5.9
2020-04-26 14:09:24.122  - [32minfo[39m: host.server iobroker NPM version: 6.14.4
2020-04-26 14:09:24.123  - [32minfo[39m: host.server iobroker npm install iobroker.coronavirus-statistics@0.5.9 --loglevel error --prefix "C:/iobroker" (System call)
2020-04-26 14:09:25.467  - [32minfo[39m: host.server iobroker npm
2020-04-26 14:09:25.468  - [32minfo[39m: host.server iobroker  ERR! Cannot read property 'resolve' of undefined
2020-04-26 14:09:25.476  - [32minfo[39m: host.server iobroker 
2020-04-26 14:09:25.477  - [32minfo[39m: host.server iobroker npm ERR! A complete log of this run can be found in:npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2020-04-26T12_09_25_467Z-debug.log
2020-04-26 14:09:25.501  - [32minfo[39m: host.server iobroker upload [4] coronavirus-statistics.admin C:/iobroker/node_modules/iobroker.coronavirus-statistics/admin/words.js words.js application/javascript
2020-04-26 14:09:25.639  - [32minfo[39m: host.server iobroker upload [3] coronavirus-statistics.admin C:/iobroker/node_modules/iobroker.coronavirus-statistics/admin/style.css style.css text/css
2020-04-26 14:09:25.711  - [32minfo[39m: host.server iobroker upload [2] coronavirus-statistics.admin C:/iobroker/node_modules/iobroker.coronavirus-statistics/admin/index_m.html index_m.html text/html
2020-04-26 14:09:25.779  - [32minfo[39m: host.server iobroker upload [1] coronavirus-statistics.admin C:/iobroker/node_modules/iobroker.coronavirus-statistics/admin/coronavirus-statistics.png coronavirus-statistics.png image/png
2020-04-26 14:09:25.843  - [32minfo[39m: host.server iobroker upload [0] coronavirus-statistics.admin C:/iobroker/node_modules/iobroker.coronavirus-statistics/admin/admin.d.ts admin.d.ts video/mp2t
2020-04-26 14:09:25.898  - [32minfo[39m: host.server iobroker Adapter "coronavirus-statistics" updated
2020-04-26 14:09:26.917  - [32minfo[39m: host.server iobroker exit 0

**Comment by Apollon77** [comment]
Please try to run the given command directly via npm to See if error happens then too. Thank you

**Comment by Apollon77** [comment]
Ps: which js-Controller?

**Comment by Apollon77** [comment]
And please provide the logfile as you can find in error message above.

**Comment by epcos71** [comment]
Hi,
thanks for your quick support :)
npm also failed. js-controller is version 2.2.9. 

Logfile is here:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'iobroker.coronavirus-statistics@0.5.9'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session 37319f351179f75f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for iobroker.coronavirus-statistics@0.5.9 Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 1770ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-fetch\index.js:88:23)
10 verbose stack     at fetchPackument (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:42:10)
10 verbose stack     at packument (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:20:10)
10 verbose stack     at getManifest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:22:10)
10 verbose stack     at manifest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:13:10)
10 verbose stack     at Object.manifest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\genfun\lib\genfun.js:15:38)
10 verbose stack     at manifest (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\lib\fetch.js:23:18)
10 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\manifest.js:24:12
10 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:488:18)
10 verbose stack     at new Promise (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose cwd C:\WINDOWS\system32
12 verbose Windows_NT 10.0.18363
13 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.coronavirus-statistics@0.5.9"
14 verbose node v12.16.2
15 verbose npm  v6.14.4
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]

**Comment by DutchmanNL** [comment]
cannot reproduce on linux environment this is an specific windows error....

```
xxx@ioBroker:/opt/iobroker$ npm i iobroker.coronavirus-statistics@latest
+ iobroker.coronavirus-statistics@0.5.9
removed 6 packages and updated 2 packages in 13.663s

19 packages are looking for funding
  run `npm fund` for details

xxx@ioBroker:/opt/iobroker$ 
```

**Comment by Apollon77** [comment]
ich tippe er hat wie auch immer bei sich einen npm Bug gefunden und getriggert. Man könnte mal npm aktualisieren um zu schauen ob er weg ist aonst dort den Bug melden. Kann der Adapter nix für

**Comment by kklepper** [comment]
`https://registry.npmjs.org/ioBroker.coronavirus-statistics => {"error":"Not found"}` 

does not look like an npm bug, does it? To me, it looks like that package is not present in the registry. At least that is exactly what the result tells.

**Comment by DutchmanNL** [comment]
> `https://registry.npmjs.org/ioBroker.coronavirus-statistics => {"error":"Not found"}`
> 
> does not look like an npm bug, does it? To me, it looks like that package is not present in the registry. At least that is exactly what the result tells.

than pleas tell me what this is : https://www.npmjs.com/package/iobroker.coronavirus-statistics

and why I can install it

**Comment by kklepper** [comment]
Please tell me what I do wrong and how I can succeed.

I know how to get the original data and I can feed my database with it and do all sorts of queries (data as of 2020-04-17). 

![image](https://user-images.githubusercontent.com/6130319/80607697-17c6e800-8a36-11ea-9439-5626893f94a3.png)

I am interested to use your tool as I think I can get the info I want more easily.

First, with your command `npm i iobroker.coronavirus-statistics@latest` I could install the package without error:

![image](https://user-images.githubusercontent.com/6130319/80607188-8192c200-8a35-11ea-9e2f-7b771580397f.png)

That is great. Why did my original approach fail?

Now what? I did a refresh on `http://localhost:8881/#tab-adapters` and did not find the package `coronavirus-statistics`. 

![image](https://user-images.githubusercontent.com/6130319/80607996-7ab87f00-8a36-11ea-900c-436afd7636e2.png)

Next I tried `https://npm.runkit.com/iobroker.coronavirus-statistics` given in `https://www.npmjs.com/package/iobroker.coronavirus-statistics` with the result

![image](https://user-images.githubusercontent.com/6130319/80607453-ce769880-8a35-11ea-99d6-036cef0e6de1.png)

Sorry, I have no clue what to do. I never heard of iobroker before. Neuland...

**Comment by epcos71** [comment]
Problem solved, I had a wrong node.js upgrade procedure. After proper install it works now, so really no issue with the adapter. Sorry :)

**Comment by DutchmanNL** [comment]
> Problem solved, I had a wrong node.js upgrade procedure. After proper install it works now, so really no issue with the adapter. Sorry :)

no problem perfect to know the root cause !
Can you please share your issue and solution just in case other have the same ?

**Comment by DutchmanNL** [comment]
> Sorry, I have no clue what to do. I never heard of iobroker before. Neuland...

Hey dude, no problem at all I am happy to help you out a little here but its getting complicated to do that by an issue as we talk about the basics :)

So you are from Germany right ? I can advise you a teamspeak community with a lot of nice people with ioBroker knowledge (including some lesser nice ones like me 👯‍♂️ ) which can assist you so you wanna join ?

What I see in basic, you are using the software a little bit the wrong way : 

1) you try to install it by NPM, not needed that's basically advanced mode
2) during the installation, you have been in the wrong directory and by that the NPM package is installed but not attached to you iobroker installation

So in basic, please use the admin to install adapter.
If you really want to install an iobroker NPM packe (hope you know what you do) you always have to be in the iobroker installation dir
/opt/iobroker
