### ISSUE TITLE
npm install ioBroker.coronavirus-statistics delivers 404

### ISSUE THREAD

**Issue by kklepper** [iobroker-community-adapters/ioBroker.coronavirus-statistics#47]
**!!! Before you start !!!**  
1. Verify if there is not already an issue requesting the same
2. Is this realy a bug of current code or an  enhancement request ?

**Describe the bug**  
D:\>npm install ioBroker.coronavirus-statistics
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ioBroker.coronavirus-statistics - Not found
npm ERR! 404
npm ERR! 404  'ioBroker.coronavirus-statistics@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**To Reproduce**  
2. Click on '...'

https://registry.npmjs.org/ioBroker.coronavirus-statistics => {"error":"Not found"}

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ioBroker.coronavirus-statistics' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 16868aeef1422015
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/ioBroker.coronavirus-statistics 3857ms
8 http fetch GET 404 https://registry.npmjs.org/ioBroker.coronavirus-statistics 1073ms
9 silly fetchPackageMetaData error for ioBroker.coronavirus-statistics@latest 404 Not Found - GET https://registry.npmjs.org/ioBroker.coronavirus-statistics - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 8912ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/ioBroker.coronavirus-statistics - Not found
12 verbose stack     at res.buffer.catch.then.body (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid ioBroker.coronavirus-statistics@latest
15 verbose cwd D:\
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ioBroker.coronavirus-statistics"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/ioBroker.coronavirus-statistics - Not found
22 error 404
23 error 404 'ioBroker.coronavirus-statistics@latest' is not in the npm registry.
24 error 404 Your package name is not valid, because
25 error 404 1. name can no longer contain capital letters
26 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 

D:\>node -v
v10.16.0

 - Operating system: <os-name>

Windows 10

**Additional context**  

Installed iobroker-1.5.14.b-windows-installer.exe

**Comment by DutchmanNL** [comment]
duplicate https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/46
