### ISSUE TITLE
Data for Netherlands not displayed when selecting "wieder gesund" to be shown

### ISSUE THREAD

**Issue by OLFDB** [iobroker-community-adapters/ioBroker.coronavirus-statistics#49]
As soon as I enable the check box "wieder gesund" for country Netherlands the whole widget gets invisible. Both the edit view and the normal view don't show data. 

Inspector in Firefox shows
TypeError: data[type] is null

Version: system.adapter.coronavirus-statistics  : coronavirus-statistics - v0.5.9

![Bildschirmfoto 2020-05-06 um 19 07 38](https://user-images.githubusercontent.com/5459286/81206816-ef5a6300-8fcc-11ea-83eb-7e86902edbfd.png)
![Bildschirmfoto 2020-05-06 um 19 06 43](https://user-images.githubusercontent.com/5459286/81207354-bbcc0880-8fcd-11ea-9364-f4ea7d1a58dc.png)

**Comment by DutchmanNL** [comment]
@GermanBluefox  can you please assist with the widget?

**Comment by DutchmanNL** [comment]
is this issue still the case ?
