### ISSUE TITLE
Missing Counter for Quarantaine

### ISSUE THREAD

**Issue by Chaot1** [iobroker-community-adapters/ioBroker.coronavirus-statistics#5]
Is it possible to add a Countdown for Quarantaine Time remaining?

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by GermanBluefox** [comment]
The information that is available can be found here: https://corona.lmao.ninja/countries
No Quarantaine time is available there
