### ISSUE TITLE
Fälle der letzten 7Tage/100.000 Einwohner im Landkreis

### ISSUE THREAD

**Issue by SGhoktar** [iobroker-community-adapters/ioBroker.coronavirus-statistics#50]
Ist es möglich, auch die Fälle der Letzten 7Tage/100.000 Einwohner mit anzugeben?

Nach dem neuen Beschluss der Bundes Republik Deutschland ist dieser Wert ja nicht unerheblich.

**Comment by DutchmanNL** [comment]
Der kommt leider nicht in der API vor könntest es da aber mal vorschlagen ;)

**Comment by SGhoktar** [comment]
Meinst du bei NPGEO?

**Comment by DutchmanNL** [comment]
in der jetzigen api (siehe readme) kommen die Daten nicht vor, sollte es eine bekannte source geben kan man neu öffnen
