### ISSUE TITLE
Fehler für Berliner Bezirke obwohl Berlin nicht genutzt wird !?

### ISSUE THREAD

**Issue by gidhap** [iobroker-community-adapters/ioBroker.coronavirus-statistics#51]
Hallo, seit heute habe ich plötzlich folgende Fehler im Log. Scheinen ja alles Berliner Bezirke zu sein, ich nutze aber Berlin nicht. Muss ich mir Gedanken machen ?

`
coronavirus-statistics.0 | 2020-05-14 16:00:50.451 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":415,"GEN":"Berlin  Tempelhof-Schöneberg","BEZ":"Bezirk","death_rate":3.24074074074074,"cases":648,"deaths":21,"cases_per_100k":184.
-- | -- | -- | --
coronavirus-statistics.0 | 2020-05-14 16:00:50.451 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":414,"GEN":"Berlin  Friedrichshain-Kreuzberg","BEZ":"Bezirk","death_rate":1.02459016393443,"cases":488,"deaths":5,"cases_per_100k":1
coronavirus-statistics.0 | 2020-05-14 16:00:50.450 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":413,"GEN":"Berlin  Mitte","BEZ":"Bezirk","death_rate":1.19176598049837,"cases":923,"deaths":11,"cases_per_100k":240.256968232979,"c
coronavirus-statistics.0 | 2020-05-14 16:00:50.450 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":412,"GEN":"Berlin  Steglitz-Zehlendorf","BEZ":"Bezirk","death_rate":2.30326295585413,"cases":521,"deaths":12,"cases_per_100k":168.7
coronavirus-statistics.0 | 2020-05-14 16:00:50.449 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":411,"GEN":"Berlin  Spandau","BEZ":"Bezirk","death_rate":2.29007633587786,"cases":262,"deaths":6,"cases_per_100k":107.387171741599,"
coronavirus-statistics.0 | 2020-05-14 16:00:50.446 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":410,"GEN":"Berlin  Marzahn-Hellersdorf","BEZ":"Bezirk","death_rate":0.595238095238095,"cases":336,"deaths":2,"cases_per_100k":125.1
coronavirus-statistics.0 | 2020-05-14 16:00:50.445 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":409,"GEN":"Berlin  Lichtenberg","BEZ":"Bezirk","death_rate":3.2967032967033,"cases":273,"deaths":9,"cases_per_100k":93.668940340090
coronavirus-statistics.0 | 2020-05-14 16:00:50.426 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":408,"GEN":"Berlin  Neukölln","BEZ":"Bezirk","death_rate":4.29184549356223,"cases":699,"deaths":30,"cases_per_100k":212.016706552499
coronavirus-statistics.0 | 2020-05-14 16:00:50.426 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":407,"GEN":"Berlin  Pankow","BEZ":"Bezirk","death_rate":3.81679389312977,"cases":655,"deaths":25,"cases_per_100k":160.631736416809,"
coronavirus-statistics.0 | 2020-05-14 16:00:50.425 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":406,"GEN":"Berlin  Treptow-Köpenick","BEZ":"Bezirk","death_rate":2.6865671641791,"cases":335,"deaths":9,"cases_per_100k":123.546484
coronavirus-statistics.0 | 2020-05-14 16:00:50.425 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":405,"GEN":"Berlin  Charlottenburg-Wilmersdorf","BEZ":"Bezirk","death_rate":3.05555555555556,"cases":720,"deaths":22,"cases_per_100k
coronavirus-statistics.0 | 2020-05-14 16:00:50.411 | error | (24053) Unknown Bezirk received containing  {"attributes":{"OBJECTID":404,"GEN":"Berlin  Reinickendorf","BEZ":"Bezirk","death_rate":4.35684647302905,"cases":482,"deaths":21,"cases_per_100k":181.7324912

`

**Comment by Kampfratte** [comment]
Diese Meldung habe ich auch seit heute drin. Und ich nutze nur den Bezirk Neukölln.

**Comment by Kampfratte** [comment]
Habe @DutchmanNL gerade einen PullRequest geschickt, in der diese Fehlerausgabe behoben ist.

**Comment by Kampfratte** [comment]
<img width="843" alt="Bildschirmfoto 2020-05-15 um 11 36 20" src="https://user-images.githubusercontent.com/37498878/82035813-5b5d5b00-96a0-11ea-911f-0e6b4a3e53d8.png">
Diese Meldungen mit dem PullRequest auch gleich behoben.

**Comment by mswiege** [comment]
Kleiner Tipp @Kampfratte: Wenn du im Pull Request "#51" anstatt nur "51" schreibst, dann verbindet Github dieses issue automatisch mit dem PR und wird so nicht so leicht übersehen.

**Comment by Kampfratte** [comment]
@mswiege ok, das wusste ich nicht. Danke für den Hinweis.

**Comment by mswiege** [comment]
Habe deinen branch bei mir installiert und die nervigen log Einträge sind weg und soweit ich das sehe funktioniert alles noch wie es soll. 👍

**Comment by Kampfratte** [comment]
jo, habe den bei mir seit dem PR auch ohne Probleme am laufen. Der fehler entstand, da in der API-Abfrage die Bezirke für Berlin geändert wurden. Denn vorher hieß "Bezirk" in der Abfrage noch "Stadt".

@DutchmanNL scheint irgendwie zur Zeit nicht on kommen zu können, denn sonst wäre der PR mit Sicherheit schon eingebaut und der Fehler bei allen erledigt.

**Comment by vaaarg** [comment]
kann mir bitte jemand sagen wie genau ich diesen pull request installiere ?

**Comment by Kampfratte** [comment]
@vaaarg der Pull Request liegt noch bei mir als fork und du kannst den über folgende URL direkt von mir installieren, ist glaube ich einfacher.

https://github.com/Kampfratte/ioBroker.coronavirus-statistics

**Comment by vaaarg** [comment]
> https://github.com/Kampfratte/ioBroker.coronavirus-statistics

super danke

**Comment by DutchmanNL** [comment]
fixed 0.6.0 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/946413e293f615fad3972c70e191f605da2802fc

Thank you @Kampfratte !
