### ISSUE TITLE
Figurse for canadian provinces ?

### ISSUE THREAD

**Issue by gidhap** [iobroker-community-adapters/ioBroker.coronavirus-statistics#54]
Hi, I'd like to see the figures for Canadian provinces.
Any Chance ?
Txs

**Comment by DutchmanNL** [comment]
I don't know any API providing it, please feel free to reopen the issue if an datasource is known

**Comment by gidhap** [comment]
Hi, just found the numbers for the provinces [https://www.nytimes.com/interactive/2020/world/canada/canada-coronavirus-cases.html#states](url), not sure about an api or so.
