### ISSUE TITLE
Erweiterte Einstellungen nicht möglich

### ISSUE THREAD

**Issue by rnc11** [iobroker-community-adapters/ioBroker.coronavirus-statistics#55]
Ich würde gern für Deutschland spezielle Landkreise auswählen.
Leider sind alle Schalter in den erweiterten Einstellungen deaktiviert.
Ich habe den Adapter bereits mehrmals neu installiert (ohne Erfolg).
Der ioBroker läuft bei mir auf einem RPI 4 mit 4GB RAM und etlichen weiteren Adaptern.

**Comment by Kampfratte** [comment]
Hast du den Adapter nach dem installieren einmal ohne die erweiterten Einstellungen eingeschalten, bzw laufen gelassen? Der Adapter muss dann nach dem ersten Start nochmal gestoppt werden, dass da was eingestellt werden kann.

**Comment by rnc11** [comment]
Ja, das hab ich gemacht. Ich habe den Adapter mehrmals gestoppt und gestartet.
Ich habe verschiedene Länder selektiert bzw. nur Deutschland ausgewählt.
Das hat alles nichts gebracht. Die erweiterten Einstellungen bleiben deaktiviert.

**Comment by rnc11** [comment]
Gibt es schon neue Info‘s? Soll ich was spezielles testen? Werden log‘s benötigt? ...

**Comment by rnc11** [comment]
Hab gerade noch einmal getestet und jetzt funktioniert es.
Vermutlich hab ich anstatt auf die Schalter-Bezeichnung immer auf das Schalter-Symbol geklickt (was man als Apple User so gewöhnt ist).
Allerdings reagiert der **Schalter** bei mir nur, wenn man direkt auf die **Bezeichnung** „Bundesländer“ ... „Landkreise“ klickt.
