### ISSUE TITLE
Warning messages in log

### ISSUE THREAD

**Issue by Dragon0501** [iobroker-community-adapters/ioBroker.coronavirus-statistics#56]
The log shows some warnings and some errors. The errors are for a not selected information. I dont need the information of Berlin.
![Fehler](https://user-images.githubusercontent.com/59663011/86337060-e5fa1980-bc50-11ea-8de2-03843de90e78.jpg)

**Comment by Kampfratte** [comment]
Hallo @Dragon0501 

We know this errors and @DutchmanNL have the Pull Request for fix it.
You can install here the fix. https://github.com/Kampfratte/ioBroker.coronavirus-statistics
I dont know, when DutchmanNL the pull Request insert it to a new version.

**Comment by Dragon0501** [comment]
Thank you very much!

**Comment by DutchmanNL** [comment]
fixed 0.6.0 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/946413e293f615fad3972c70e191f605da2802fc

Thank you @Kampfratte !
