### ISSUE TITLE
Berlin districts not resolved 

### ISSUE THREAD

**Issue by vdi-cloud** [iobroker-community-adapters/ioBroker.coronavirus-statistics#57]
Hi, 
when selecting Berlin, districts are not resolved and are hence not in the list of objects. There is an error log per district:  "Unknown Bezirk received containing {"attributes":...".

**Comment by Kampfratte** [comment]
Hallo @vdi-cloud 

We know this errors and @DutchmanNL  have the Pull Request for fix it.
You can install here the fix. https://github.com/Kampfratte/ioBroker.coronavirus-statistics
I dont know, when DutchmanNL the pull Request insert it to a new version.

**Comment by vdi-cloud** [comment]
Ok, thanks. I will try it out.

**Comment by DutchmanNL** [comment]
fixed 0.6.0 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/946413e293f615fad3972c70e191f605da2802fc

Thank you @Kampfratte !
