### ISSUE TITLE
Objects not updating

### ISSUE THREAD

**Issue by adilimbau88** [iobroker-community-adapters/ioBroker.coronavirus-statistics#58]
Hello,

i am running the coronavirus-statistics adapter on 2 different RPis. Currently i am having problems on one of them getting the objects updated (initially i could not select the countries, it just loaded and loaded). Now i am able to select the countries and it adds the corresponding new objects, but the 15min update of the objects is not working. Have tried reinstalling the adapter, that does an update for the moment, but that is about it. Sometimes i am also not able to remove the instance and objects created by the adapter.

On the second RPi everything seems to be running fine. Any ideas what might cause this?

Adrian

After deleting adapter and trying to access settings
![grafik](https://user-images.githubusercontent.com/46246304/87549953-c3371e80-c6ae-11ea-8097-a5731a6b8d32.png)

![grafik](https://user-images.githubusercontent.com/46246304/87549802-8c610880-c6ae-11ea-9f02-3bca72b642ad.png)

**Comment by DutchmanNL** [comment]
@arteck would it be possible for you to test this in your multihost environment ?

**Comment by DutchmanNL** [comment]
@adilimbau88 is this issue still actual ?

**Comment by adilimbau88** [comment]
Hello, i did not tested it anymore, as i have used another solution for coronavirus statistics. As it seems to be related to my RPi setup (working on another RPi), i guess it can be closed. Thank you!
