### ISSUE TITLE
Statistik für die Bundesländer

### ISSUE THREAD

**Issue by Brati79** [iobroker-community-adapters/ioBroker.coronavirus-statistics#6]
Hallo,

wäre es möglich auch die Zahlen für die 16 Bundesländer in Deutschland auszulesen? 

Grüße

Brati

**Comment by DutchmanNL** [comment]
Hi, wen jemand ne API findet wo ich die Daten abfragen kann klar ... ich kenne aber keine ;)

**Comment by Brati79** [comment]
Hmm,

ich finde nur diese Seite, aber die müsste man dann parsen:

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

Grüße

Brati

**Comment by Brati79** [comment]
Das wird hier schon besprochen:

https://forum.iobroker.net/topic/31026/parser-corona-fallzahlen/2

**Comment by DutchmanNL** [comment]
Aber sehr instabiel da schraubt man immerzu an der Tabelle

Man könnte das Parser - Regex Prinzip übernehmen aber das sieht sehr unstabil aus

**Comment by Brati79** [comment]
Ja, das macht dann nur nebenbei Sinn aber nicht hier im Adapter...

**Comment by DutchmanNL** [comment]
Jup, aber wen jemand ne gute Source hat gerne her damit baue ich sofort ein

**Comment by DutchmanNL** [comment]
Ich schließe  das issue auch als reference da es momentan. keine gute Möglichkeit zur Umsetzung gibt.

Sollte jemand ne API haben für  die Daten  immer her damit und machen wirs

**Comment by DutchmanNL** [comment]
API gefunden 👯‍♂ issue re-opend

https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0

**Comment by DutchmanNL** [comment]
ab 0.4.2 integriert https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/147324ecba3f7ac85b34ec84c5f9872afc56dc12
