### ISSUE TITLE
Possibility to only request Country

### ISSUE THREAD

**Issue by reptil1990** [iobroker-community-adapters/ioBroker.coronavirus-statistics#7]
Could we get a possibility to pick certain Countrys in an option menu?
It reduces the load on the API and not everyone needs all the data from ever country.

Thanks :)

**Comment by DutchmanNL** [comment]
yes its on my to do will work on it this weekend

**Comment by DutchmanNL** [comment]
implemented in 0.3.0

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/2f6b0d782f4339a1539c4090535d8b73d9a829db
