### ISSUE TITLE
Erhalte immer wieder eine Warnmeldung im Log

### ISSUE THREAD

**Issue by simpixo** [iobroker-community-adapters/ioBroker.coronavirus-statistics#9]
Diese Warnmeldung erscheint alle 15 Minuten im iobroker LOG -> (6519) Cabo_Verde not found in lib! Must be added to the country name translator.

**Comment by DutchmanNL** [comment]
Neue Version kommt heute Mittag fix ist bereits als PR angeboten 😁

**Comment by DutchmanNL** [comment]
solved 0.2.5 https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/commit/6fe2b9aee346bb5995b529fb0fe5ffda85bea7e0
